### ISSUE TITLE
Retrain Tokenizer for Python

### ISSUE THREAD

**Issue by USSiamaboat** [MichiganDataScienceTeam/F24-mini-copilot#21]
https://huggingface.co/learn/nlp-course/en/chapter6/2 
Follow this:
1. Load GPT-2 Tokenizer
2. Create iterator dataset for our training data
3. Train GPT-2 Tokenizer with iterator
4. Save weights to file

**Comment by USSiamaboat** [comment]
Draft: https://github.com/MichiganDataScienceTeam/F24-mini-copilot/commit/b4f1f3cc0f6c046cf3d747ce09d056fc48cf53a2

**Comment by maximk27** [comment]
Is this completed and good to close?

**Comment by USSiamaboat** [comment]
yes
