### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by USSiamaboat** [MichiganDataScienceTeam/F24-mini-copilot#33]
- Safe and debounced calls to cloud model
- Inline code suggestions
- ???

Anyone want to work on this?
https://github.com/MichiganDataScienceTeam/F24-mini-copilot/tree/feat/extension

**Comment by maximk27** [comment]
Debouncing and inline suggestions working on old api. Just change URL when latest is deployed. https://github.com/MichiganDataScienceTeam/F24-mini-copilot/commit/a6bda3ea181507ccbec2b2d1c5231767417a75bd
Possible extra feature:
- Add in app chat bot. Use GPT-2 api
